// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xzvafzivobwdknvivxwi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6dmFmeml2b2J3ZGtudml2eHdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgzMDM1ODUsImV4cCI6MjA4Mzg3OTU4NX0.Pz79pABFShkE9ZY5_-9EDYT1yvFYK60y_1DMbsEB7L8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});